<a href="https://colab.research.google.com/github/Shubhranshu-Malhotra/Coursera-TensorFlow-Specialization/blob/main/Coursera_tf_course1_practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
x = np.asarray([-2,-1, 0, 1, 2, 3, 4, 5])
y = np.asarray(3*x)-2

In [ ]:
x,y

(array([-2, -1,  0,  1,  2,  3,  4,  5]),
 array([-8, -5, -2,  1,  4,  7, 10, 13]))

In [ ]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(1,input_shape = (1,)))
model.compile(optimizer = 'sgd', loss = 'mean_squared_error')

In [ ]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x,y,epochs=200)

Epoch 1/200
1/1 [==============================] - 0s 218ms/step - loss: 75.9811
Epoch 2/200
1/1 [==============================] - 0s 4ms/step - loss: 55.3383
Epoch 3/200
1/1 [==============================] - 0s 5ms/step - loss: 40.6198
Epoch 4/200
1/1 [==============================] - 0s 5ms/step - loss: 30.1164
Epoch 5/200
1/1 [==============================] - 0s 4ms/step - loss: 22.6124
Epoch 6/200
1/1 [==============================] - 0s 4ms/step - loss: 17.2428
Epoch 7/200
1/1 [==============================] - 0s 6ms/step - loss: 13.3923
Epoch 8/200
1/1 [==============================] - 0s 3ms/step - loss: 10.6233
Epoch 9/200
1/1 [==============================] - 0s 5ms/step - loss: 8.6244
Epoch 10/200
1/1 [==============================] - 0s 8ms/step - loss: 7.1740
Epoch 11/200
1/1 [==============================] - 0s 4ms/step - loss: 6.1146
Epoch 12/200
1/1 [==============================] - 0s 8ms/step - loss: 5.3341
Epoch 13/200
1/1 [==============================] -

In [ ]:
model.predict([7])

array([[18.904446]], dtype=float32)